### ISSUE TITLE
Reorg the docs

### ISSUE THREAD

**Issue by treeder** [gochain-io/docs#35]
Probably some cleanup we can do here:

* put aws, azure, private-chains, nodes/custom, nodes/local into the same top level folder
* /tokens under /corp
* not sure what rtp is?

**Comment by jmank88** [comment]
> not sure what rtp is?

`rtd` was read-the-docs source, but we have since switched. @ialexander28 Can the `rtd` directory be removed? (can always be retrieved from history if necessary)

Are we worried about preserving links we have already given out?
