### ISSUE TITLE
How many RAM need to have for docker in testnet

### ISSUE THREAD

**Issue by KursLabIgor** [gochain-io/docs#37]
Currently i have 4GB and it works unstable and time to time crash, and reason that no left RAM . 
8GB enough?

**Comment by treeder** [comment]
We recommend 32GB, but 16GB is probably minimum.

**Comment by jmank88** [comment]
If you are using the testnet docker-compose file (https://github.com/gochain-io/docs/blob/master/nodes/testnet/docker-compose.yml) then you should set `GOCHAIN_CACHE` to something lower - it defaults to 4GBs.

**Comment by KursLabIgor** [comment]
@jmank88 i set 512. 
Wow 16 GB. 
But for mainnet docker i dont have such problem. WDYT?

**Comment by jmank88** [comment]
The mainnet currently has much lower volume. The testnet has been undergoing load tests for 6 months.

**Comment by KursLabIgor** [comment]
Do we have ability to limit usage resources?

**Comment by jmank88** [comment]
You can try limiting the docker containers resources: https://docs.docker.com/config/containers/resource_constraints/

**Comment by KursLabIgor** [comment]
i used your docker-compose file. where as i know for V3 exist defect for limit resources. 
OK, i'll try build from sources and check memory consumption in this case. closed until now.
