### ISSUE TITLE
I need to sync chain in full mode

### ISSUE THREAD

**Issue by KursLabIgor** [gochain-io/docs#38]
Hi, i need to integrate gochain node plus blockscout block explorer. For this need to sync db in full mode, i use your solution with docker-compose
Could you confirm that such command sync chain in full mode? 
command: gochain --datadir gochain/node --cache ${GOCHAIN_CACHE:-512} --rpc --ws --ipcdisable --rpcaddr 0.0.0.0 --wsaddr 0.0.0.0 --wsorigins * *--syncmode full*

**Comment by jmank88** [comment]
Yes, that should work AFAIK

**Comment by KursLabIgor** [comment]
how i can check from log that db syncing in full mode. and what about trace mode? because blockscout requires trace mode enabled , for example for Ethereum. do we have similar for gochain ?

**Comment by jmank88** [comment]
I'm not sure about the logs, but you should be able to query an old state via JSONRPC to verify that it is keeping them around. We haven't modified these areas of the code base, so all of the go-ethereum docs for tracing and syncmode should still apply.

**Comment by KursLabIgor** [comment]
ok. closed. until now.
